dist: bionic
os: linux
language: python

services:
  - docker

install:
  - bash ./tests/install.sh

jobs:
  include:
    - stage: Testing if a user can login with a simple password
      script:
        - bash ./tests/sshpassword.sh
    - stage: Testing if a user can login with ssh key
      script:
        - bash ./tests/sshkey.sh