dist: bionic
os: linux
language: python
branches:
  only:
  - master
  - testing
services:
- docker
install:
- bash ./tests/install.sh
jobs:
  include:
  - stage: Running the tests
    script:
    - shellcheck tests/*.sh
    - docker run --rm -i -v "$PWD/tests/hadolint.yaml":/root/.config/hadolint.yaml hadolint/hadolint < Dockerfile
    - shellcheck ./*.sh
    - bash ./tests/sshpassword.sh
    - bash ./tests/sshkey.sh
    - bash ./tests/sshshell.sh
  - stage: Pushing the images
    if: branch IN (master, main, testing)
    script:
    - bash ./tests/push.sh
env:
  global:
  - secure: mHgMQ3Rt/gdWi9l4q817g6/XyIiuD/KvfkzRJfVy2LxNNfQZRYpR/0eRnJRdVgbKmFySHUIy7y+8Mfdixg6KkIWc4jvodWe/7D9dXsLLB5e9ndXHhGTvMucZCcM80W5PJoG7N2YScWSW9wUw4ZaHXO63VL64WCcy/h+XCP76TGpFy/TWodePoPh6lS0y6gs4BwBjBZFqzmHSSSSRdhen8Upn/shxJ3hVdWLdlnu0FA/A0kB1IBO1eR2vizZ9JHs4IjB5q7BfruKwbmUOMtCyluL8CQktazkbJ495XwWl2ZGXsP42pI4SkkY4wlgnWQJ23Fit/OMDixDHT/vrDSY/JrrECIRJihv6PkqQuM9knaOgYBQnxbfE22IsaCcenrGAXLiJcE61PMgAoh5PSJQtpdVTily8Erunhw6e2MVPzcoWQHZ69n0gdmfulXfg87bVHly1LvqH0ZX34AKfh1DY159I369PP/FM1fa14PFrbRh9+sbpLUDCyTYGJHjnEJc7CBzZeWXpP66QF/3yfFzmhSNstygVg8jrHLZMhrIqEfQKBPNtu0m4jY35TKSQurBomwYFFst3+GiJrDxged4zq/Fenk5NHPQT0gfYg5JY7UGgnWWGqmj5C6hp4/4fSyALJNvYcc0EVUfRdzKg6lLCUoxAXmdcF6CbCpIeqpKpwSc=
  - secure: rZ1s1z1TYRd14Sj5sqpjBtVLQGOMD1bYEE50XODgzJfh4YA/q1f5x927SdP9n0NMRquZHQkGuXQ4AMMr0Dsrku6X1Tpdag5OHx4k2QKsAtodx/NEPQPw2aTcpyNcMgb2fcQs7C4aIpVpUUT/ubG+L3Sb3vdKkaWv8fcuoaAx/G9rmRH2lWPELAjvJ4p0mnXS+94RHykYUqTL9bAv884ZLcYbaFWK0zo8JNSNJaXwX9+Ido/VyPnD/e0nbyeDd6n/SlhYx6DFAGIInh23fco80u8nZ/yXHs6K6pi9dDe3bRSF5G6mWajk1ZpJqCbRsfm+LhEwNXmhQUF9cOBdxiUnI7XruOn5s8qOcnXTcEK6ZR7YSYIdivUy1Pxv5XkznEqAsxw2dbB7QEw/xye9x1vQVbuz2MBPbO2R0QMOFfujTUN73YgXj7y2I1G4LpY8uopW7pGVrbwjT3WYz3CuhspeHh8x1Vwedi8vq0UTH0kYZm81jZ+vRNpGshj4M3OmOB6IiCY7CnIEa5Ip3ymO/3GX6vXQRh4U9Q5QQMb09aW9t6Nop10vfkRzm6q+ahWuGLPpUl4B4ir7xlSVaDdR3FXQyJrvndO9qm4Hh5YLuCz6NTgwnA24xzC7lMn/0jOuOWD3ksMeshB3zozPF91kXw87wKey/86c7/km/468xd4uwng=
